In [3]:
# 문제1

In [8]:
import pandas as pd
import numpy as  np

In [14]:
a= np.array(10)

In [15]:
print(a,a.ndim,a.shape)

10 0 ()


In [16]:
# 문제2

In [20]:
arr = np.array([1,2,3,4,5])

In [21]:
print(arr.dtype,arr.size)

int64 5


In [22]:
#문제3

In [23]:
m = np.array([[1,2,3],[4,5,6]])

In [24]:
print(m.ndim,m.shape)

2 (2, 3)


In [25]:
#문제4

In [26]:
x = np.array(['1','2','3'])

In [28]:
print(x,x.dtype)

['1' '2' '3'] <U1


In [29]:
#문제5

In [30]:
r = np.arange(0,10)

In [31]:
print(r,r.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [32]:
#문제6

In [40]:
r2 = np.arange(1,11,2)
r2

array([1, 3, 5, 7, 9])

In [39]:
#문제7

In [33]:
m = np.arange(0,12)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
m = m.reshape(3,4)
print(m,m.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [41]:
#문제8

In [42]:
m2 = m.reshape(4,3)
print(m2.shape)

(4, 3)


In [45]:
#문제9
k = np.array([[1,2],[3,4]])
k

array([[1, 2],
       [3, 4]])

In [46]:
k.flatten()

array([1, 2, 3, 4])

In [47]:
#문제10

In [48]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [49]:
#문제11

In [54]:
print(r[0],r[9],r[:3])

0 9 [0 1 2]


In [79]:
#문제12
b = np.arange(12).reshape(3,4)

In [80]:
print(b[0])
print(b[:,-1])

[0 1 2 3]
[ 3  7 11]


In [84]:
#문제13
sub = b[1,0:2]
print(sub)

[4 5]


In [ ]:
#문제14

In [96]:
c = np.arange(25).reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [98]:
diag = c.diagonal()
diag.flatten()

array([ 0,  6, 12, 18, 24])

In [99]:
#문제15

In [107]:
d = np.arange(12).reshape(4,3)
print(d[2:4])

[[ 6  7  8]
 [ 9 10 11]]


In [108]:
#문제16

In [110]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [115]:
new_arr = arr[::2]
print(new_arr)

[10 30 50]


In [136]:
#문제17
picked = []
e = np.arange(16).reshape(4,4)
picked.append(e[0,1])
picked.append(e[1,2])
picked.append(e[2,3])

In [137]:
picked

[np.int64(1), np.int64(6), np.int64(11)]

In [156]:
#문제18
sub2 = e[::2,1:4:2]
print(sub2)

[[ 1  3]
 [ 9 11]]


In [163]:
#문제19
x = np.array([3,6,9,12,15,18])
print(x > 10)

[False False False  True  True  True]


In [165]:
#문제20
arr2D = np.arange(12).reshape(3,4)
arr2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
arr2D%2 == 0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [184]:
#문제21
v = np.arange(5)
print(v + 10)

[10 11 12 13 14]


In [191]:
#문제22
A = np.arange(6).reshape(2,3)
B = np.array([10,10,10])
print(A+B)

[[10 11 12]
 [13 14 15]]


In [195]:
#문제23
print(np.sum(A,axis=1))
print(np.sum(A,axis=0))

[ 3 12]
[3 5 7]


In [198]:
#문제24
M = np.arange(9).reshape(3,3)
print(np.mean(M))
print(np.mean(M,axis=0))

4.0
[3. 4. 5.]


In [209]:
#문제25
data = np.array([5,-2,7,-9,0])
cleande = np.where(data > 0 ,data , 0)
print(cleande)

[5 0 7 0 0]


In [213]:
#문제26
arr = np.arange(10)
label = np.where(arr%2 == 0,"even","odd")
print(label)

['even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd']


In [214]:
#문제27
X = np.array([[1,2],[3,4]])
Y = np.array([[10,20],[30,40]])

In [215]:
print(X+Y)
print(X*Y)

[[11 22]
 [33 44]]
[[ 10  40]
 [ 90 160]]


In [ ]:
#문제28
