In [1]:
# 문제1

In [2]:
import pandas as pd
import numpy as  np

In [3]:
a= np.array(10)

In [4]:
print(a,a.ndim,a.shape)

10 0 ()


In [5]:
# 문제2

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
print(arr.dtype,arr.size)

int64 5


In [8]:
#문제3

In [9]:
m = np.array([[1,2,3],[4,5,6]])

In [10]:
print(m.ndim,m.shape)

2 (2, 3)


In [11]:
#문제4

In [12]:
x = np.array(['1','2','3'])

In [13]:
print(x,x.dtype)

['1' '2' '3'] <U1


In [14]:
#문제5

In [15]:
r = np.arange(0,10)

In [16]:
print(r,r.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [17]:
#문제6

In [18]:
r2 = np.arange(1,11,2)
r2

array([1, 3, 5, 7, 9])

In [19]:
#문제7

In [20]:
m = np.arange(0,12)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
m = m.reshape(3,4)
print(m,m.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [22]:
#문제8

In [23]:
m2 = m.reshape(4,3)
print(m2.shape)

(4, 3)


In [24]:
#문제9
k = np.array([[1,2],[3,4]])
k

array([[1, 2],
       [3, 4]])

In [25]:
k.flatten()

array([1, 2, 3, 4])

In [26]:
#문제10

In [27]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
#문제11

In [29]:
print(r[0],r[9],r[:3])

0 9 [0 1 2]


In [30]:
#문제12
b = np.arange(12).reshape(3,4)

In [31]:
print(b[0])
print(b[:,-1])

[0 1 2 3]
[ 3  7 11]


In [32]:
#문제13
sub = b[1,0:2]
print(sub)

[4 5]


In [33]:
#문제14

In [322]:
c = np.arange(25).reshape(5,5)
c.diagonal()

array([ 0,  6, 12, 18, 24])

In [35]:
diag = c.diagonal()
diag.flatten()

array([ 0,  6, 12, 18, 24])

In [36]:
#문제15

In [37]:
d = np.arange(12).reshape(4,3)
print(d[2:4])

[[ 6  7  8]
 [ 9 10 11]]


In [38]:
#문제16

In [326]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [327]:
new_arr = arr[::2]
print(new_arr)

[10 30 50]


In [41]:
#문제17
picked = []
e = np.arange(16).reshape(4,4)
picked.append(e[0,1])
picked.append(e[1,2])
picked.append(e[2,3])

In [42]:
picked

[np.int64(1), np.int64(6), np.int64(11)]

In [43]:
#문제18
sub2 = e[::2,1:4:2]
print(sub2)

[[ 1  3]
 [ 9 11]]


In [44]:
#문제19
x = np.array([3,6,9,12,15,18])
print(x > 10)

[False False False  True  True  True]


In [45]:
#문제20
arr2D = np.arange(12).reshape(3,4)
arr2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
arr2D%2 == 0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [47]:
#문제21
v = np.arange(5)
print(v + 10)

[10 11 12 13 14]


In [48]:
#문제22
A = np.arange(6).reshape(2,3)
B = np.array([10,10,10])
print(A+B)

[[10 11 12]
 [13 14 15]]


In [49]:
#문제23
print(np.sum(A,axis=1))
print(np.sum(A,axis=0))

[ 3 12]
[3 5 7]


In [50]:
#문제24
M = np.arange(9).reshape(3,3)
print(np.mean(M))
print(np.mean(M,axis=0))

4.0
[3. 4. 5.]


In [51]:
#문제25
data = np.array([5,-2,7,-9,0])
cleande = np.where(data > 0 ,data , 0)
print(cleande)

[5 0 7 0 0]


In [52]:
#문제26
arr = np.arange(10)
label = np.where(arr%2 == 0,"even","odd")
print(label)

['even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd']


In [53]:
#문제27
X = np.array([[1,2],[3,4]])
Y = np.array([[10,20],[30,40]])

In [54]:
print(X+Y)
print(X*Y)

[[11 22]
 [33 44]]
[[ 10  40]
 [ 90 160]]


In [55]:
#문제28
print(X@Y)

[[ 70 100]
 [150 220]]


In [56]:
#문제29
f = np.array([1.2,2.7,4.5])
g = f.astype(int)
g.dtype

dtype('int64')

In [57]:
#문제30
z = np.array([0,0,1,1,1,2,2,3])
unique_vals = np.unique(z)
print(unique_vals)

[0 1 2 3]


In [58]:
#문제31
s = np.array([5,1,9,3])
print(np.sort(s))

[1 3 5 9]


In [59]:
#문제32
sgrs = np.argsort(s)
sgrs

array([1, 3, 0, 2])

In [60]:
#문제33
arr2 = np.array([[3,1],[2,4]])
np.sort(arr2,axis=1)

array([[1, 3],
       [2, 4]])

In [61]:
#문제34
arr2 = np.array([[3,1],[2,4]])
np.sort(arr2,axis=0)

array([[2, 1],
       [3, 4]])

In [62]:
#문제35
w = np.array([10,40,20,30])
np.argmax(w)

np.int64(1)

In [63]:
#문제 36
np.argmin(w)

np.int64(0)

In [64]:
#문제37 
q = np.arange(12).reshape(3,4)
np.argmax(q,axis=1)

array([3, 3, 3])

In [65]:
#문제38
np.argmin(q,axis=0)

array([0, 0, 0, 0])

In [66]:
#문제39
mix = np.array([3,3,2,1,2,3,0])
np.unique(mix)

array([0, 1, 2, 3])

In [67]:
#문제40
L = np.linspace(0,10,6)
np.sort(L)[::-1]

array([10.,  8.,  6.,  4.,  2.,  0.])

In [68]:
#문제41
a = np.array([1,2,3])
b = np.array([4,5,6])
merged = np.concatenate((a,b))
merged

array([1, 2, 3, 4, 5, 6])

In [69]:
#문제42
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [70]:
#문제43
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [71]:
#문제44
# x의 문자 배열은 3이고 y의 문자 배열은 2이 때문에 서로 배열 길이기 달라서 합칠 수 없다.
x = np.array([[1,2,3]])
y = np.array([[4,5]])
np.concatenate((x,y),axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [72]:
#45
Z = np.arange(6).reshape(2,3)
Z_T = Z.transpose()
print(Z_T)
print(Z_T.shape)

[[0 3]
 [1 4]
 [2 5]]
(3, 2)


In [73]:
#46
Y = np.array([[1,2],[3,4],[5,6]])
Y.T

array([[1, 3, 5],
       [2, 4, 6]])

In [74]:
#47
R = np.arange(12).reshape(2,2,3)
print(R.shape)
print(R.ndim)

(2, 2, 3)
3


In [75]:
#48
print(R[0])
print(R[1])

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [76]:
#49
R2 = R +100
print(R2)

[[[100 101 102]
  [103 104 105]]

 [[106 107 108]
  [109 110 111]]]


In [77]:
#50
sum0 = np.sum(R,axis = 0)
print(sum0)
print(sum0.shape)

[[ 6  8 10]
 [12 14 16]]
(2, 3)


In [78]:
#51 
score = np.array([95,60,72,88,45])
np.where(score >= 70, "pass" , "fail")

array(['pass', 'fail', 'pass', 'pass', 'fail'], dtype='<U4')

In [79]:
#52
tr = score > 80
high = score[tr]
print(high)

[95 88]


In [80]:
#53
print(np.mean(score))
k = score >= np.mean(score)
print(score[k])

72.0
[95 72 88]


In [81]:
#54
temp = np.array([[10,-5],[3,-1],[0,7]])
fixed = np.where(temp > 0,temp,0)
print(fixed)

[[10  0]
 [ 3  0]
 [ 0  7]]


In [82]:
#55
mask = np.where(temp >= 0,False,True)
print(mask)
print(temp[mask])

[[False  True]
 [False  True]
 [False False]]
[-5 -1]


In [83]:
#56
arr = np.arange(1,13).reshape(3,4)
new_arr = np.where(arr%2 == 0,arr,arr*-1)
new_arr

array([[ -1,   2,  -3,   4],
       [ -5,   6,  -7,   8],
       [ -9,  10, -11,  12]])

In [84]:
#57
np.max(arr,axis=1)

array([ 4,  8, 12])

In [85]:
#58
np.min(arr,axis=0)

array([1, 2, 3, 4])

In [86]:
#59
np.std(arr)

np.float64(3.452052529534663)

In [87]:
#60
np.var(arr)

np.float64(11.916666666666666)

In [88]:
#61
cube = np.arange(24).reshape(2,3,4)
print(cube.shape)
print(cube.ndim)

(2, 3, 4)
3


In [89]:
#62
print(cube[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [90]:
#63
cube2 = cube+100
print(cube2[1,2,3])

123


In [91]:
#64
print(np.sum(cube,axis=0))
print(np.sum(cube,axis=1))
print(np.sum(cube,axis=2))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


In [92]:
#65
t = cube.transpose(1,0,2)
print(t.shape)

(3, 2, 4)


In [93]:
#66
mean_last = np.mean(cube,axis=2)
print(mean_last)
print(mean_last.shape)

[[ 1.5  5.5  9.5]
 [13.5 17.5 21.5]]
(2, 3)


In [94]:
#67
vec = np.arange(1,6)
print(vec.reshape(5,1))
print(vec.reshape(1,5))

[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


In [95]:
#68
a = vec.reshape(5,1)
b = vec.reshape(1,5)
mat = a*b
print(mat.shape)
print(mat)

(5, 5)
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [96]:
#69
M = np.arange(1,10).reshape(3,3)
M2 = M.copy()      
np.fill_diagonal(M2, 0)
print(M2)

[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [97]:
#70
row_indices, col_indices = np.triu_indices(M.shape[0], k=1)
upper = M[row_indices, col_indices]
print(upper)

[2 3 6]


In [98]:
#71
zeros = np.arange(0,9)
np.zeros_like(zeros)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [99]:
#72
ones = np.ones((3,4))
print(ones)
print(ones.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [100]:
#73
sevens = np.full((2,3),7)
print(sevens)

[[7 7 7]
 [7 7 7]]


In [105]:
#74
a = np.array([1,2,3,4,5])
m = np.mean(a)
print(a-m)

[-2. -1.  0.  1.  2.]


In [106]:
#75
p = np.array([2,4,6])
q = np.array([1,3,5])
print(p-q)
print(p*q)
print(p/q)

[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]


In [116]:
#76
arr = np.array([1,2,0,4,0,5])
nonzero_vals = arr[arr > 0]
print(nonzero_vals)

[1 2 4 5]


In [126]:
#77
idx_zero = np.where(arr == 0)
print(idx_zero)

(array([2, 4]),)


In [132]:
#78
G = np.arange(1,10).reshape(3,3)
print(np.sum(G))
print(np.sum(np.trace(G)))

45
15


In [153]:
#79
rev_rows =G[::-1]
print(rev_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [188]:
#80
rev_cols = G[:,::-1]
print(rev_cols)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [189]:
#81
h = np.arange(10)
h2 = np.where(h%2==0,h+100,h)
print(h2)

[100   1 102   3 104   5 106   7 108   9]


In [190]:
#82
src = np.array([10,20,30,40,50])
src[1:4] = 0
dst = src
print(dst)

[10  0  0  0 50]


In [193]:
#83
H = np.arange(16).reshape(4,4)
mask_arr = np.zeros_like(H)
mask_arr[0, :] = H[0, :]      
mask_arr[-1, :] = H[-1, :]    
mask_arr[:, 0] = H[:, 0]      
mask_arr[:, -1] = H[:, -1]
print(mask_arr)

[[ 0  1  2  3]
 [ 4  0  0  7]
 [ 8  0  0 11]
 [12 13 14 15]]


In [195]:
#84
center = H[1:3,1:3]
print(center)

[[ 5  6]
 [ 9 10]]


In [208]:
#85
K = np.arange(1,17).reshape(4,4)
row_mean = np.mean(K,axis=1)
row_mean

array([ 2.5,  6.5, 10.5, 14.5])

In [205]:
#86
np.mean(K,axis=0)

array([ 7.,  8.,  9., 10.])

In [216]:
#87
row_mean =row_mean.reshape(4,1)
K-row_mean

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [218]:
#88
t = np.array([1,2,3,4,5])
print(np.cumsum(t))

[ 1  3  6 10 15]


In [219]:
#89
print(np.cumprod(t))

[  1   2   6  24 120]


In [239]:
#90
U = np.arange(9).reshape(3,3)
print(U)
U2 = np.triu(U)
print(U2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [0 4 5]
 [0 0 8]]


In [241]:
#91
height = np.array([170,180,175,160,165])
print(np.mean(height))
print(np.max(height))
print(np.min(height))

170.0
180
160


In [259]:
#92
tall_group = np.where(height >= np.mean(height))
tall_group

(array([0, 1, 2]),)

In [265]:
#93
sales = np.arange(1,13).reshape(3,4)
month_sum= np.sum(sales,axis=0)
print(month_sum)

[15 18 21 24]


In [268]:
#94
branch_mean = np.mean(sales,axis=1)
print(branch_mean)

[ 2.5  6.5 10.5]


In [320]:
#95
a = np.argmax(sales,axis=0)
b = np.argmax(sales,axis=1)
print(np.unique(a))
print(np.unique(b))

[2]
[3]


In [314]:
#96
scores = np.array([88,92,75,90,68,100])
scores = np.sort(scores)
scores[3:][::-1]

array([100,  92,  90])

In [292]:
#97
print(np.mean(scores))
print(np.std(scores))

85.5
10.766460266339475


In [293]:
#98
product = np.array([10,20,30,40])
cost = np.array([7,15,22,35])
profit = product - cost
print(profit)

[3 5 8 5]


In [301]:
#99
perc = ((product/cost)-1)*100
print(perc)

[42.85714286 33.33333333 36.36363636 14.28571429]


In [304]:
#100
data = np.array([[5,2,7],[1,9,3],[4,6,8]])
max_col = np.max(data,axis=0)
print(max_col)

[5 9 8]
